sudo: required
language: c
before_install:
- sudo apt-get update
- sudo apt-get install gcc
- sudo apt-get install python3
- sudo apt-get install python3-pip
- sudo apt-get install ninja-build
- pip3 install meson
script:
- meson build && cd build
- ninja
- ninja test
