sudo: required
language: c
before_install:
- sudo apt-key update
- sudo apt-get update -q
# - sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
- sudo apt-get -y install build-essential
- sudo apt-get -y --force-yes install linux-headers-`uname -r`
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
- sudo apt-get install gcc
- sudo apt-get install python3
- sudo apt-get install python3-pip
- sudo apt-get install ninja-build
- sudo pip3 install meson
script:
- meson build && cd build
- ninja
- ninja test
